# 新しい行の前に改行をいれるか　falseでいれない。
add_newline = false

# シンボルを "❯" から"➜"に変更する
[character]
success_symbol = "[➜](bold green)"
# ディレクトリパスのスタイルを変更する
error_symbol = "[ ::](#FF5555)"
vicmd_symbol = "[ ::](#55FF55)"

[directory]
style = "bold cyan"


[hostname]
ssh_only = true
disabled = false
style = "#ffff3f"

[docker_context]
symbol = "🐋 "

[git_status]
#conflicted = "🏳"
#ahead = "🏎💨"
#behind = "😰"
#diverged = "😵"
untracked = "🤷‍"
#stashed = "📦"
modified = "🍔"
staged.value = "++"
taged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "👅"
deleted = "🌼"

[aws]
symbol = "☁️  "
style = "#ff9900"
[aws.region_aliases]
ap-northeast-1 = "tokyo"
ap-northeast-3 = "osaka"
us-east-1 = "va"
us-east-2 = "oh"
us-west-1 = "ca"
us-west-2 = "or"